name: Deploy to surge.sh workflow

on: push

jobs:
  my-job:
    name: Deploy to surge.sh job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to surge.sh
        uses: dswistowski/surge-sh-action@v1.0.2
        with:
          domain: ${{ secrets.SURGE_DOMAIN }}
          project: '.'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
